[package]
name = "bronze_loop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cycle_map = "0.2.0"
lazy_static = "1.4.0"
regex = "1.9.5"
unicode-segmentation = "1.10.1"
